1: exercicio3_parte1.cpp
	make clear
	g++ exercicio3_parte1.cpp -o main
2: exercicio3_parte2.cpp
	make clear
	g++ exercicio3_parte2.cpp -o main
3: exercicio3_parte3.cpp
	make clear
	g++ exercicio3_parte3.cpp -o main
clear:
	rm -f main
run: ./main
	./main
