1: exercicio3_parte1.cpp
	g++ exercicio3_parte1.cpp -o 1
	./1
2: exercicio3_parte2.cpp
	g++ exercicio3_parte2.cpp -o 2
3: exercicio3_parte3.cpp
	g++ exercicio3_parte3.cpp -o 3
	./3
clean:
	rm -f 1 2 3
